### ISSUE TITLE
Рамка и основная надпись

### ISSUE THREAD

**Issue by mrPTqp** [xSilverSx/Spec#1]
День добрый! Скачал ваш проект, мне нравится! Но спецификация при печати не соответствует ГОСТу (размеры рамки и основной надписи). Не подскажете как обойти этот момент? Плюс, по ГОСТу необходимо под основной надписью указывать формат листа. Могу ли я как-то редактировать сам шаблон (интересует графика и шрифт)?

**Comment by xSilverSx** [comment]
Добрый день!
Для регулировки размеров рамки и основной надписи (справа снизу которая) регулируется шириной строк и колонок в Экселе (вообще я регулировал именно по ГОСТу, если расхождения, то это надо ругать Эксель или принтер) строки/колонки вставлять/удалять нельзя, ширину можно регулировать как угодно
Ту часть основной надписи что слева, к сожалению отрегулировать не получится, слишком сложно это сделать программно, а более красивого пути решения я к сожалению не нашел (там видно что границы привязаны к ячейкам)
Указание форматки под основной надписью я не предусмотрел... да и думаю не все принтеры ее распечатают, но если принтер сможет распечатать, то как вариант можно можно воспользоваться фигурами "Вставка - Фигуры" выбрать текст и проставить в том месте формат, аналогичным образом делаются изменения, Вставляем флажок и пишем то что необходимо.

Ограничений по редактирования шрифтов я не вижу, но есть кое-какие моменты которые надо предусмотреть
1. Разные шрифты имеют разное наполнение, поэтому если будут сильные расхождения при переносе надо отредактировать соответствующую ширину колонки на листе "Перенос" (в книге шаблон для спецификации) этот лист программно скрывается его надо отобразить.
2. Необходимо отредактировать лист "Шаблоны" в Надстройке (аналогично скорректировать шрифты),
       Для этого:
- На вкладке "Спецификация" нажимаем кнопку "Включить" в разделе "Работа с базой" (это отобразит нам все листы надстройки)
- Меняем шрифты на листе "Шаблоны"
- Снова жмем на кнопку "Включить" (скрываем листы надстройки, если этого не сделать файл надстройки не удастся сохранить)
- Нажимаем "Сохранить книгу" там же (эта кнопка сохраняет файл надстройки)

Кажется ничего не забыл :-)

**Comment by mrPTqp** [comment]
Большое спасибо за подробный ответ! Будем экспериментировать дальше!

**Comment by xSilverSx** [comment]
В новой версии решил вопрос с основной надписью слева, за счет добавления картинок в колонтитул (видны они только при печати (или в предпросмотре)
